publish_mode: editorial_workflow
backend:
  name: github
  auth_scope: repo
  repo: ProjectDrawdown/open-collaboratory
  open_authoring: true
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      create: true
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Link", name: "link", widget: "string"}
        - { label: "Header Image", name: "header_image", widget: "file"}
        - { label: "Project Image", name: "project_image", widget: "file"}
        - { label: "Bottom Image", name: "bottom_image", widget: "file"}
        - label: 'Projects'
          name: "projects"
          widget: "relation"
          collection: "projects"
          value_field: "{{fields.name}}__{{fields.description}}__{{fields.link}}__{{slug}}"
          search_fields: ["name"]
          multiple: true
  - name: "projects"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    label: "Projects"
    folder: "projects"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Active", name: "active", widget: "boolean", required: false}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Link", name: "link", widget: "string"}
      - { label: "Collaborators", 
          name: "collaborators", 
          widget: "relation", 
          collection: "authors", 
          value_field: "name", 
          search_fields: ["name"],
          multiple: true   
        }
      - { label: "Video Link", name: "video", widget: "string", required: false }
  - name: "resources"
    label: "Resources"
    folder: "resources"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "File", name: "file", widget: "file", required: false}
      - { label: "Link", name: "link", widget: "string", required: false}
      - label: 'Related Projects'
        name: "projects"
        widget: relation
        collection: "projects"
        value_field: "name"
        search_fields: ["name"]
        multiple: true
        required: false
  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Nickname", name: "nickname", widget: "string"}

